apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: hello-world-petset
  release: 'v1.0'
spec:
  serviceName: "hello-world-service"
  replicas: 3 
  template:
    metadata:
      labels:
        app: hello-world-petset
        release: 'v1.0'
    spec:
      terminationGracePeriodSeconds: 0
      volumes:
      - name: shared
        persistentVolumeClaim:
          claimName: shared
      containers:
      - name: busybox 
        readinessProbe:
          exec:
            command:
              - "echo"
          initialDelaySeconds: 5
        volumeMounts:
        - name: data
          mountPath: /data
        - name: shared
          mountPath: /data/shared
        image: centos:7
        command:
          - 'sleep'
        args:
          - '3600'
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 15Gi
